In [1]:
import numpy as np
import pandas as pd


In [2]:
pip install tensorflow_datasets

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import pandas as pd

In [35]:
from tensorflow.keras import datasets

In [5]:
datasets

<module 'keras.api._v2.keras.datasets' from 'C:\\Users\\taran\\anaconda3\\Lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\__init__.py'>

In [6]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np
import pandas as pd

In [8]:
from tensorflow_datasets import datasets

In [9]:
datasets

<module 'tensorflow_datasets.datasets' (<_frozen_importlib_external.NamespaceLoader object at 0x000001C35FC957D0>)>

In [10]:
pip install tensorflow

In [11]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [12]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [13]:
x_train.shape,

((60000, 28, 28),)

In [14]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [15]:
x_test.shape

(10000, 28, 28)

In [16]:
#img_row,img_cols=

In [17]:
width,height=28,28
input_shape=(width,height,1)
input_shape

(28, 28, 1)

In [18]:
x_train=x_train.reshape(x_train.shape[0],height,width,1)

In [19]:
x_test=x_test.reshape(x_test.shape[0],height,width,1)

In [20]:
x_train.shape,y_train.shape

((60000, 28, 28, 1), (60000,))

In [21]:
from sklearn.model_selection import train_test_split


In [22]:
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.1)
len(x_val)

6000

# normalizing Data/Scalling

In [23]:
x_train=(x_train - x_train.mean())/x_train.std()
x_val=(x_val - x_val.mean())/x_val.std()
x_test=(x_test - x_test.mean())/x_test.std()

In [24]:
from tensorflow import keras

# Format Data

In [25]:
num_labels=10
y_train=keras.utils.to_categorical(y_train)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [26]:
y_val=keras.utils.to_categorical(y_val)
y_test=keras.utils.to_categorical(y_test)

# Built Our Model

In [27]:
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

# Lenet 5 _arch

In [28]:
model=Sequential()

In [29]:
model.add(Conv2D(6, kernel_size=(5,5), strides=(1,1), activation='tanh', input_shape=(28,28,1)))

model.add(AveragePooling2D(pool_size=(2,2),strides=(1,1)))

model.add(Conv2D(16,kernel_size=(5,5),strides=(1,1),activation='tanh'))

model.add(AveragePooling2D(pool_size=(2,2),strides=(2,2)))

model.add(Conv2D(120,kernel_size=(5,5),strides=(1,1),activation='tanh'))

model.add(Flatten()) 
model.add(Dense(84,activation='tanh'))
model.add(Dense(num_labels,activation='softmax'))

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (Average  (None, 23, 23, 6)         0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Avera  (None, 9, 9, 16)          0         
 gePooling2D)                                                    
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten (Flatten)           (None, 3000)              0

In [31]:
model.compile(loss=keras.losses.categorical_crossentropy, optimizer= 'adam' ,metrics= ['accuracy'])

# Training 

In [32]:
history=model.fit(x_train, y_train, batch_size=32, epochs=5, verbose= 1, validation_data=(x_val, y_val))

Epoch 1/5
1688/1688 [==============================] - 78s 44ms/step - loss: 0.1886 - accuracy: 0.9436 - val_loss: 0.0999 - val_accuracy: 0.9723
Epoch 2/5
1688/1688 [==============================] - 79s 47ms/step - loss: 0.0885 - accuracy: 0.9739 - val_loss: 0.0922 - val_accuracy: 0.9748
Epoch 3/5
1688/1688 [==============================] - 74s 44ms/step - loss: 0.0774 - accuracy: 0.9769 - val_loss: 0.0831 - val_accuracy: 0.9752
Epoch 4/5
1688/1688 [==============================] - 76s 45ms/step - loss: 0.0671 - accuracy: 0.9797 - val_loss: 0.0858 - val_accuracy: 0.9758
Epoch 5/5
1688/1688 [==============================] - 79s 47ms/step - loss: 0.0627 - accuracy: 0.9811 - val_loss: 0.0683 - val_accuracy: 0.9793


In [33]:
score= model.evaluate(x_test, y_test, verbose=1) 

313/313 [==============================] - 6s 19ms/step - loss: 0.0520 - accuracy: 0.9849


In [34]:
score

[0.05196361616253853, 0.9848999977111816]